'use client';

import React from 'react';
import { SectionHeader } from '@/components/common/SectionHeader';
import { History, CheckCircle2 } from 'lucide-react';

export interface ExportHistoryRecord {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedTime: string;
  exportFormat: 'CSV' | 'Excel' | 'PDF' | 'Print';
  rowCount: number;
}

interface ExportHistoryLogProps {
  history: ExportHistoryRecord[];
}

export const ExportHistoryLog: React.FC<ExportHistoryLogProps> = ({ history }) => {
  return (
    <div className="ww-card p-6 shadow-card space-y-4">
      <SectionHeader
        icon={<History className="w-5 h-5 text-[#08C565]" />}
        title="Export Audit & Activity History"
        subtitle="Log of recently generated and exported business reports"
        badgeText="Activity Log"
      />

      <div className="overflow-x-auto">
        <table className="ww-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Generated By</th>
              <th>Generated Time</th>
              <th className="text-center">Format</th>
              <th className="text-right">Rows</th>
            </tr>
          </thead>
          <tbody>
            {history.length === 0 ? (
              <tr>
                <td colSpan={5} className="py-6 text-center text-[#6B7280] italic">
                  No exports performed in the current session. Click any export button above to generate a report file.
                </td>
              </tr>
            ) : (
              history.map((record) => (
                <tr key={record.id}>
                  <td className="font-bold text-[#111827] flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-[#08C565]" />
                    <span>{record.reportName}</span>
                  </td>

                  <td className="text-[#374151]">
                    {record.generatedBy}
                  </td>

                  <td className="text-[#6B7280] font-mono text-xs">
                    {record.generatedTime}
                  </td>

                  <td className="text-center">
                    <span
                      className={
                        record.exportFormat === 'Excel'
                          ? 'badge-success'
                          : record.exportFormat === 'CSV'
                          ? 'badge-info'
                          : record.exportFormat === 'PDF'
                          ? 'badge-danger'
                          : 'badge-warning'
                      }
                    >
                      {record.exportFormat}
                    </span>
                  </td>

                  <td className="text-right font-mono font-bold text-[#111827]">
                    {record.rowCount}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
